/*
 * This file was generated by the Gradle 'init' task.
 */

val ktorVersion: String by rootProject
val koinVersion: String by rootProject

plugins {
    id("kotlin-application-conventions")
}

dependencies {
    api(projects.app.adapters.env)
    api(projects.app.adapters.persist)
    api(projects.app.adapters.remoting)
    api(projects.app.adapters.primaryWeb)
    api(projects.app.core)

    implementation("io.ktor:ktor-server-core:$ktorVersion")
    implementation("io.ktor:ktor-server-netty:$ktorVersion")
    implementation("io.insert-koin:koin-ktor:$koinVersion")
}

application {
    // Define the main class for the application.
    mainClass.set("infra.AppKt")
}
